FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG POSTGRES_HOST
ARG POSTGRES_PORT
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB

ARG APP_PORT

RUN npm run build

ENV \
POSTGRES_HOST=$POSTGRES_HOST \
POSTGRES_PORT=$POSTGRES_PORT \
POSTGRES_USER=$POSTGRES_USER \
POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
POSTGRES_DB=$POSTGRES_DB \
APP_PORT=${APP_PORT}

EXPOSE ${APP_PORT}

USER node

CMD ["node", "dist/main", "--port", "${APP_PORT}"]